# Generated by Django 5.2.5 on 2025-08-10 01:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('done', 'Завершено'), ('failed', 'Ошибка')], default='queued', max_length=20, verbose_name='Статус')),
                ('progress', models.IntegerField(default=0, help_text='Прогресс выполнения от 0 до 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс (%)')),
                ('task_metadata', models.JSONField(default=dict, help_text='JSON с метаданными: информация о файлах, параметрах конвертации и т.д.', verbose_name='Метаданные задачи')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Задача конвертации',
                'verbose_name_plural': 'Задачи конвертации',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='converter_c_status_cf95b7_idx'), models.Index(fields=['created_at'], name='converter_c_created_a9819a_idx'), models.Index(fields=['-created_at'], name='converter_c_created_a2a119_idx')],
            },
        ),
    ]
