# Generated by Django 5.2.5 on 2025-08-10 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('original_path', models.CharField(blank=True, max_length=512, verbose_name='Путь к оригинальному файлу')),
                ('output_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя выходного файла')),
                ('output_path', models.CharField(blank=True, max_length=512, verbose_name='Путь к результату конвертации')),
                ('output_url', models.URLField(blank=True, verbose_name='URL результата конвертации')),
                ('file_type', models.CharField(choices=[('video', 'Видео'), ('image', 'Изображение'), ('audio', 'Аудио'), ('document', 'Документ'), ('archive', 'Архив'), ('other', 'Другой')], default='other', max_length=20, verbose_name='Тип файла')),
                ('input_format', models.CharField(max_length=10, verbose_name='Входной формат')),
                ('output_format', models.CharField(max_length=10, verbose_name='Выходной формат')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер исходного файла (байты)')),
                ('output_size', models.BigIntegerField(blank=True, default=0, verbose_name='Размер результата (байты)')),
                ('status', models.CharField(choices=[('completed', 'Завершено'), ('failed', 'Ошибка')], default='completed', max_length=20, verbose_name='Статус конвертации')),
                ('engine_used', models.CharField(blank=True, max_length=50, verbose_name='Используемый движок')),
                ('processing_time', models.FloatField(default=0.0, verbose_name='Время обработки (секунды)')),
                ('conversion_params', models.JSONField(blank=True, default=dict, help_text='JSON с параметрами конвертации', verbose_name='Параметры конвертации')),
                ('result_metadata', models.JSONField(blank=True, default=dict, help_text='JSON с информацией о результате конвертации', verbose_name='Метаданные результата')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес пользователя')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'История конвертации',
                'verbose_name_plural': 'История конвертаций',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_type'], name='converter_c_file_ty_5e5acb_idx'), models.Index(fields=['status'], name='converter_c_status_429ce0_idx'), models.Index(fields=['created_at'], name='converter_c_created_693d1c_idx'), models.Index(fields=['-created_at'], name='converter_c_created_14a09f_idx'), models.Index(fields=['input_format', 'output_format'], name='converter_c_input_f_7e966a_idx')],
            },
        ),
    ]
